### ISSUE TITLE
Feature request : better log integration with kubernetes

### ISSUE THREAD

**Issue by lefebsy** [ca-gip/kubi#10]
Hi,

Kubernetes can deal with both containers streams `stdout` and `stderr` as described here https://kubernetes.io/docs/concepts/cluster-administration/logging/

`Kubi.utils.Log` method send every log level to `stdout`, even _fatal_ or _panic_.

A filebeat log collector is able to forward metadata `stdout` or `stderr` in _stream_ field.

**Please**, monitoring Kubi could be easier with a `stderr` filter enabled :-)

**Comment by efortin** [comment]
Done, err are redirected to stderr, token review is printed in json format
