### ISSUE TITLE
Features - Kubi client integration

### ISSUE THREAD

**Issue by lefebsy** [ca-gip/kubi#18]
Hello,

The cli new subcommands are great !

1) New cli subcommands and new releases  are a little treaky to detect in user shell scripts or Theia/VScode wrappers, maybe a `--kubi-client-version` and `--kubi-server-version`or something  similar could help to handle changes

2) Just an idea, maybe kubi-cli could try to also follow the `kubectl-plugin` naming convention ?https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins
Being able to be discovered and distributed by `Krew` should increase Kubi visibility in kubectl/kubernetes communities.
`kubectl kubi config update --username mylogin --kubi-url https://kubi.mycluster.local`

**Comment by evrardjp** [comment]
I agree on the convention for kubectl.

Yet, we can't simply update kubi interface without breaking some users.

I believe there are other tasks to tackle before this one, particularily a cleanup of the code and reuse of external components.
