### ISSUE TITLE
kubi-deployment - ecdsa-key.pem: no such file or directory

### ISSUE THREAD

**Issue by MisterBlueBear** [ca-gip/kubi#19]
The kubi-api and kubi-webhook containers fail to start both with a "Unable to read ECDSA private key: open /var/run/secrets/ecdsa/ecdsa-key.pem: no such file or directory" error.
The kubi-operator works fine, but I can't figure out why the others don't.

$ kubectl logs kubi-deployment-5cb4488c4-gpbpr kubi-api -n kube-system
2020-11-14T00:24:58Z FTL Unable to read ECDSA private key: open /var/run/secrets/ecdsa/ecdsa-key.pem: no such file or directory
$ kubectl logs kubi-deployment-5cb4488c4-gpbpr kubi-webhook -n kube-system
2020-11-14T00:27:43Z FTL Unable to read ECDSA private key: open /var/run/secrets/ecdsa/ecdsa-key.pem: no such file or directory

**Kubernetes versions**
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:15:05Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by evrardjp** [comment]
We can certainly close this support request by now :)
