### ISSUE TITLE
Feature request: Add namespace metrics

### ISSUE THREAD

**Issue by leto1210** [ca-gip/kubi#9]
Hello,

Is it possible to add on /metrics informations about namespace ?
- Number of Namespace created
- Number of Namespace created on error
- Number of Namespace present managed by kubi

Regards,

**Comment by augabet** [comment]
Looks like a good use case, have you think about contributing ? cc @efortin

**Comment by efortin** [comment]
On going

**Comment by clementblaise** [comment]
Check out our new release Grafana dashboard and metrics have been added with #15
